name: 'AssetOrganizer'
description: 'Analyze and detect unused assets in iOS/macOS projects'
author: 'mkemalgokce'

branding:
  icon: 'trash-2'
  color: 'red'

inputs:
  project-path:
    description: 'Path to the project directory to analyze'
    required: true
    default: '.'
  output-format:
    description: 'Output format (md, json)'
    required: false
    default: 'md'
  min-size:
    description: 'Minimum size threshold (e.g., 100KB, 1MB)'
    required: false
    default: '0'
  asset-type:
    description: 'Asset type to analyze (image, color, data)'
    required: false
    default: 'all'

runs:
  using: 'composite'
  steps:
    - name: Install AssetOrganizer
      shell: bash
      run: |
        if ! command -v AssetOrganizer &> /dev/null; then
          echo "Installing AssetOrganizer..."
          # Get latest release info from GitHub API
          LATEST_RELEASE=$(curl -s https://api.github.com/repos/mkemalgokce/AssetOrganizer/releases/latest)
          DOWNLOAD_URL=$(echo "$LATEST_RELEASE" | grep "browser_download_url.*zip" | cut -d '"' -f 4)
          VERSION=$(echo "$LATEST_RELEASE" | grep "tag_name" | cut -d '"' -f 4)
          
          echo "Installing version: $VERSION"
          curl -L "$DOWNLOAD_URL" -o AssetOrganizer.zip
          unzip AssetOrganizer.zip
          chmod +x AssetOrganizer
          sudo mv AssetOrganizer /usr/local/bin/
        else
          echo "AssetOrganizer is already installed"
        fi
    
    - name: Analyze Assets
      shell: bash
      run: |
        OPTIONS=""
        if [ "${{ inputs.output-format }}" != "" ]; then
          OPTIONS="$OPTIONS -o report.${{ inputs.output-format }}"
        fi
        if [ "${{ inputs.min-size }}" != "0" ]; then
          OPTIONS="$OPTIONS -m ${{ inputs.min-size }}"
        fi
        if [ "${{ inputs.asset-type }}" != "all" ]; then
          OPTIONS="$OPTIONS -t ${{ inputs.asset-type }}"
        fi
        
        # Run analysis
        AssetOrganizer analyze -d ${{ inputs.project-path }} $OPTIONS
        
        # Add results to step summary
        if [ "${{ inputs.output-format }}" = "json" ]; then
          echo '```json' >> $GITHUB_STEP_SUMMARY
          cat report.json >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
        else
          cat report.md >> $GITHUB_STEP_SUMMARY
        fi
        
        # Check if analysis found any issues
        if [ -s report.${{ inputs.output-format }} ]; then
          echo "::warning::Found unused assets in the project"
        else
          echo "::notice::No unused assets found"
        fi
    
    - name: Upload Report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: asset-analysis-report
        path: report.*
